spring:
  config:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bootcamp37/configurationService
          clone-on-start: false
          default-label: main
        health:
          enabled: true
server:
  port: 8888
